/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ["class"],
  content: [
    "./pages/**/*.{ts,tsx}",
    "./components/**/*.{ts,tsx}",
    "./app/**/*.{ts,tsx}",
    "./src/**/*.{ts,tsx}",
    "*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      fontFamily: {
        syne: ["var(--font-syne)", "sans-serif"],
        sans: ["Public Sans", "Inter", "sans-serif"],
        "body-lg": ["Public Sans", "sans-serif"],
        "body-md": ["Public Sans", "sans-serif"],
        "headline-md": ["Fraunces", "serif"],
        "display-lg": ["Fraunces", "serif"],
        "data-mono": ["IBM Plex Mono", "monospace"],
        "label-caps": ["Public Sans", "Inter", "sans-serif"],
      },
      fontSize: {
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "500" }],
        "display-lg": ["40px", { lineHeight: "48px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "data-mono": ["13px", { lineHeight: "18px", fontWeight: "450" }],
        "label-caps": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" }],
      },
      spacing: {
        "stack-sm": "8px",
        "container-padding": "32px",
        "stack-lg": "24px",
        "stack-md": "16px",
        "gutter": "24px",
        "sidebar-width": "240px",
      },
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "#fbf9f3",
        foreground: "#1b1c18",
        "ink-navy": "#16213E",
        paper: "#F7F5EF",
        brass: "#B8863B",
        hairline: "#E4DFD3",
        steel: "#5C6B72",
        "alert-rust": "#B8503A",
        "settled-green": "#3F7350",
        "delivery-blue": "#3A6EA5",
        primary: {
          DEFAULT: "#010a27",
          container: "#16213e",
          fixed: "#dae1ff",
          "fixed-dim": "#bbc5eb",
          foreground: "#ffffff",
        },
        secondary: {
          DEFAULT: "#505f76",
          container: "#d1e1fb",
          "fixed-dim": "#b8c7e2",
          "fixed": "#d4e3fe",
          foreground: "#ffffff",
        },
        tertiary: {
          DEFAULT: "#140a00",
          container: "#321e00",
          "fixed": "#ffddb3",
          "fixed-dim": "#f5bc6c",
          foreground: "#ffffff",
        },
        surface: {
          DEFAULT: "#fbf9f3",
          tint: "#535d7e",
          container: "#f0eee8",
          "container-low": "#f5f3ed",
          "container-high": "#eae8e2",
          "container-highest": "#e4e2dd",
          variant: "#e4e2dd",
          bright: "#fbf9f3",
          dim: "#dcdad4",
        },
        "on-primary": "#ffffff",
        "on-primary-container": "#7e89ab",
        "on-primary-fixed": "#0f1a37",
        "on-primary-fixed-variant": "#3b4665",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#55637a",
        "on-secondary-fixed": "#0c1c30",
        "on-secondary-fixed-variant": "#39485d",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#b18036",
        "on-tertiary-fixed": "#291800",
        "on-tertiary-fixed-variant": "#624000",
        "on-background": "#1b1c18",
        "on-surface": "#1b1c18",
        "on-surface-variant": "#45464d",
        outline: "#76767e",
        "outline-variant": "#c6c6ce",
        error: {
          DEFAULT: "#ba1a1a",
          container: "#ffdad6",
        },
        "on-error": "#ffffff",
        "on-error-container": "#93000a",
        "inverse-primary": "#bbc5eb",
        "inverse-surface": "#30312d",
        "inverse-on-surface": "#f3f1eb",
        destructive: {
          DEFAULT: "#ba1a1a",
          foreground: "#ffffff",
        },
        muted: {
          DEFAULT: "#e4e2dd",
          foreground: "#76767e",
        },
        accent: {
          DEFAULT: "#f5bc6c",
          foreground: "#140a00",
        },
        popover: {
          DEFAULT: "#ffffff",
          foreground: "#1b1c18",
        },
        card: {
          DEFAULT: "#ffffff",
          foreground: "#1b1c18",
        },
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
        md: "0.375rem",
        sm: "0.25rem",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        "pulse-slow": "pulse 3s cubic-bezier(0.4, 0, 0.6, 1) infinite",
      },
    },
  },
  plugins: [require("tailwindcss-animate"), require("@tailwindcss/typography")],
}

